# Generated by Django 4.1.3 on 2022-11-09 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='ecommerce_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ListedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
    ]
